<?php

namespace ShopBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name)
    {
        return $this->findOneBy(['name' => $name]);
    }
}
