# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        ShopBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_user:
            entity: { class: ShopBundle:User, property: username }

    firewalls:
        secured_area:
            pattern: ^/

            anonymous: true

            form_login:
                check_path: security_login

                login_path: security_login

                csrf_token_generator: security.csrf.token_manager

            logout:
                path: security_logout

                target: homepage

    access_control:
